### PR TITLE
Upgrade travis to trusty environment

### PR DESCRIPTION
**Pull request by mneudert**
__work in progress__

Removes any direct requirements to the "sudo: enabled" travis infrastructure and migrates to "dist: trusty".

[ref piwik/piwik#11986]

### CODE REVIEW

**Comment by mattab** [comment]
Hi @mneudert - thanks for creating this PR! 
How is the progress going so far? 
Let us know when we can review/test this further and hopefully merge it :+1:

**Comment by mneudert** [comment]
With the `LoginLdap`-PR merged only the `SystemTests` (see [last build here](https://travis-ci.org/mneudert/piwik/builds/275552297)) and the `UITests` need to be checked/adapted to run using the new `dist: trusty` setting. Probably needs some cleanup afterwards or modifications for plugin tests but it is looking quite good at the moment :slightly_smiling_face:

**Comment by mattab** [comment]
@mneudert Do you know if MySQL runs off the RAM in trusty?
(I remember this was a reason we couldn't use the "Sudo less" setup before, because MySQL and our build was too slow when not running off the RAM. )

**Comment by mneudert** [comment]
The `SystemTests` and `IntegrationTests` (and therefore `AllTests`) will keep using `sudo: required` even after the switch to trusty. Keeping the sudo requirement allows keeping the ramdisk available because without it the time required for aforementioned suites raises from 25 minutes to 45 minutes.

**Comment by mneudert** [comment]
The tests are now mostly working so I would say this is ready for a quick review. Changes currently only target core testing with the intent to not break any plugins and switch them over in a second pass. With one or two additional steps of cleanup and perhaps extension/restructuring.

Caveats:
- Occasionaly a test from the `SystemTests` suite seems to break with a change in the order of the results checked. This might be a result of the default `MySQL` version change from `5.5` to `5.6` or completely unrelated.
- The `UITests` suite is partially broken, perhaps due to some change in `gd` (`FreeType Support` changed from `true` to `false`). Ignoring the minor changes in font rendering (resulting in something like a `3px difference` failure) some tests seem to not generate any image at all.

Next step is to ensure I have not broken any plugin testing environment...

**Pull request merged**
